### ISSUE TITLE
Menu truncated and transparent (Chrome)

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub-modules-gallery#10]
Menu is truncated (z-index value not sufficient). Too transparent to my taste too.

![schermafbeelding 2017-06-10 om 18 35 03](https://user-images.githubusercontent.com/6781157/27004588-8db0929c-4e0b-11e7-9f69-55fece939ca1.png)

Martin.

**Comment by BastusIII** [comment]
Hi,

you can change the style in your theme. Please have a look at the css you use for 
``.nav-pills and ``
``.dropdown-menu``
and change it as you wish.

In the HumHub Theme this looks like 
![grafik](https://user-images.githubusercontent.com/4225867/27643360-1db67bc2-5c21-11e7-8964-f333a64fa4ff.png) which I think is fine.
