### ISSUE TITLE
Gallery of posted media files shows text from post

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub-modules-gallery#11]
Gallery of posted media files shows full text from post for some images/posts.
![schermafbeelding 2017-06-10 om 18 39 00](https://user-images.githubusercontent.com/6781157/27004616-317ac73a-4e0c-11e7-892d-39ebb2487484.png)

Martin

**Comment by BastusIII** [comment]
Hi Martin,

It was caused by insufficient html encoding of the post's description and will be fixed with the next version.

Basti

**Comment by martinbeek** [comment]
Thanks! Great! 
Love this module!
