### ISSUE TITLE
Gallery plugin cannot be deactivated

### ISSUE THREAD

**Issue by poeticpenguin** [humhub/humhub-modules-gallery#15]
Hello there,

I've got a problem with this plugin.

At first, it seemed to work fine. 
But somehow, a user uploaded pictures to a certain space using the Gallery module, causing pages which include the gallery, to not open at all anymore.

Opening the space causes this error:
![error_space_1](https://user-images.githubusercontent.com/27803194/27629477-c44d3a5e-5bf2-11e7-8426-802eb79f1d41.png)

Translation in short form: "Internal error occured".

The log says:

> $_GET = [ 'r' => 'gallery/list' 'sguid' => '1e556be0-85f9-4e73-a609-27120864c1a0' ] $_SERVER = [ 'HTTPS' => 'on' 'SSL_TLS_SNI' => 'intra.mycompany.de' 'HTTP_HOST' => 'intra.mycompany.de' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_REFERER' => 'https://intra.mycompany.de/index.php?r=calendar%2Fview%2Findex&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8' 'HTTP_COOKIE' => '__utma=139493682.1385203151.1480931311.1481107962.1493794986.4; __utmz=139493682.1480931311.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); language=4475f6b4f2e697c997636f021a854db7c5c3bb60d6dcf32735f7c9c1376952e0a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; PHPSESSID=j8e3kueh3a93l37rh3mg0c15q2; _csrf=ed784e9eb2fd7164289a6a024444b0a649f2258dd9df407df3c93bf07098b3f3a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22R%01%0F%C1%15%AE%BD%1B%0F%E8%EDV%F4%7B%E7%80%F7%10%FF%AA%D8%FE%11%AD%3C%1E8%9AG%AD-%82%22%3B%7D; pm_getting-started-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_custom-snippet-1=expanded; pm_space-members-panel=expanded; _identity=34c775f826d497f98364757feb1a95d629be179740ddc6f032d21e14be0eaa5da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%220b0dd521-3546-4ccd-84fe-eb34d2f4d72e%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.18 (Ubuntu) Server at intra.mycompany.de Port 443</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.18 (Ubuntu)' 'SERVER_NAME' => 'intra.mycompany.de' 'SERVER_ADDR' => '192.168.246.43' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '10.9.0.193' 'DOCUMENT_ROOT' => '/var/www/html/' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/' 'SERVER_ADMIN' => '[no address given]' 'SCRIPT_FILENAME' => '/var/www/html/index.php' 'REMOTE_PORT' => '55789' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=gallery%2Flist&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'REQUEST_URI' => '/index.php?r=gallery%2Flist&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1498640528.007 'REQUEST_TIME' => 1498640528 ]

The gallery-module itself seems to work fine with other spaces, though...
![error_space_2](https://user-images.githubusercontent.com/27803194/27629529-f04324fc-5bf2-11e7-8e9a-eac747162ab7.png)

What i have tried:

- Removing the gallery-module from the space = Doesn't work, error code below:

> $_GET = [ 'r' => 'space/manage/module/disable' 'moduleId' => 'gallery' 'sguid' => '1e556be0-85f9-4e73-a609-27120864c1a0' ] $_SERVER = [ 'HTTPS' => 'on' 'SSL_TLS_SNI' => 'intra.mycompany.de' 'HTTP_HOST' => 'intra.poet.de' 'HTTP_CONNECTION' => 'keep-alive' 'CONTENT_LENGTH' => '0' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ORIGIN' => 'https://intra.mycompany.de' 'HTTP_X_CSRF_TOKEN' => 'YhBA5hdbuVT6rWWIKnTyaxgSkVxgbwPNB8dZV3iqUNowEU8nAvUET_VFiN7eDxXr7wJu9riREmA72WHNPwd9WA==' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_REFERER' => 'https://intra.mycompany.de/index.php?r=space%2Fmanage%2Fmodule&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8' 'HTTP_COOKIE' => '__utma=139493682.1385203151.1480931311.1481107962.1493794986.4; __utmz=139493682.1480931311.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); language=4475f6b4f2e697c997636f021a854db7c5c3bb60d6dcf32735f7c9c1376952e0a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; PHPSESSID=j8e3kueh3a93l37rh3mg0c15q2; _csrf=ed784e9eb2fd7164289a6a024444b0a649f2258dd9df407df3c93bf07098b3f3a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22R%01%0F%C1%15%AE%BD%1B%0F%E8%EDV%F4%7B%E7%80%F7%10%FF%AA%D8%FE%11%AD%3C%1E8%9AG%AD-%82%22%3B%7D; pm_getting-started-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_custom-snippet-1=expanded; pm_space-members-panel=expanded; pm_space-gallery-snippet=expanded; _identity=34c775f826d497f98364757feb1a95d629be179740ddc6f032d21e14be0eaa5da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%220b0dd521-3546-4ccd-84fe-eb34d2f4d72e%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.18 (Ubuntu) Server at intra.mycompany.de Port 443</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.18 (Ubuntu)' 'SERVER_NAME' => 'intra.mycompany.de' 'SERVER_ADDR' => '192.168.246.43' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '10.9.0.193' 'DOCUMENT_ROOT' => '/var/www/html/' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/' 'SERVER_ADMIN' => '[no address given]' 'SCRIPT_FILENAME' => '/var/www/html/index.php' 'REMOTE_PORT' => '57046' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'POST' 'QUERY_STRING' => 'r=space%2Fmanage%2Fmodule%2Fdisable&moduleId=gallery&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'REQUEST_URI' => '/index.php?r=space%2Fmanage%2Fmodule%2Fdisable&moduleId=gallery&sguid=1e556be0-85f9-4e73-a609-27120864c1a0' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1498641334.001 'REQUEST_TIME' => 1498641334 ]

- Uninstalling it from the administration module = Same
- Removing it from the modules-directory = Causes ALL links and spaces to not work at all.

What else can i do beside restoring the whole VM?

Thanks in advance!

Cheers
poeticpenguin

**Comment by BastusIII** [comment]
Hi poeticpenguin,

do you have more information about the images causing the crash? I would like to reproduce and investigate this bug, as it seems pretty bad.
What are "pages which include the gallery"? Is the problem only occuring in the gallery view itsself (http://localhost/humhub_v1.2/s/gallery2/gallery/list) or in the whole corrupted space?

As the problems seem to be caused by some problematic images, you could try to remove those images directly from the database and start an integrity check from the console afterwards to also remove dependencies to the deleted files (yii integrity/run).
To do so, delete the files (probably the newest) from the table `gallery_media`, that have the id of the corrupted gallery in the filed gallery_id. Do not remove the whole gallery directly from the table `gallery_gallery` as the integrity check currently doesn't clean up properly after you do so.

Good Luck,
Basti

**Comment by BastusIII** [comment]
Also, your error log only shows the request and not the exception/error that is caused by it. It would be helpful to have that information, too. You should see it in the admin menu under Information->Logging, too.

It shoud be something like this:
`
Wed, 21 Jun 2017 17:56:42 +0200  yii\base\ErrorException:4096
exception 'yii\base\ErrorException' with message 'Argument 1 passed to humhub\modules\gallery\models\SquarePreviewImage::applyFile() must be an instance of humhub\modules\file\models\File, instance of humhub\modules\post\models\Post given, called in C:\htdocs\humhub_modules_v1.2\humhub-modules-gallery\models\SquarePreviewImage.php ......
`

**Comment by poeticpenguin** [comment]
@BastusIII No, the Exception/Error was NOT shown in the log. For a few days, there were no logs at all. I don't know what exactly causes this, but it could be just my installation. Probably something is filtering them...

About your questions

1. Our HumHub consists of different spaces. One of them is read/write-able for everyone. In this space, a user added the gallery and uploaded some pictures. Some pictures might be a bit huge, i have to admit. However, even if a picture is that big, HumHub and PHP have set a upload-limit per file at 42MB, so pictures of about 6MB shouldn't be a problem.

![pictures](https://user-images.githubusercontent.com/27803194/27633495-caa07170-5bff-11e7-800e-0dbf8d16fc36.png)
2. The space has got a "stream" which displays posts from every module which is added to the space. If a module is corrupted like in this case, the stream cannot be shown. It would try to display a module but fail, so it's showing nothing.

3. We've just restored the VM and HumHub works again. I will now try to upload these huge files again using the module and try your solution. Hopefully, it will work this time.

**Comment by poeticpenguin** [comment]
@BastusIII 
Hi there, it seems to be working again. I don't know what exactly caused it, but somehow HumHub resetted the Max_Upload_Size back to 5MB, although i have already increased it a months ago. Probably caused by the HumHub update itself?

So i assume: If you try to upload a picture which is bigger (filesize) than allowed by HumHub (or/and PHP), it will break.

Is it possible to catch it?

**Comment by BastusIII** [comment]
@poeticpenguin 
Hmm, it should already catch the error and not break :). I just tried it myself and had no problems in uploading a file with 17mb and 4000x5333. 

At first the upload limit was the default 5mb, which caused an error message that "Could not upload the file because it exceeds the file limit" as expected. After increasing the limit in the admin menu (Settings->Advanced->Files) to 42mb which was your value, it was alright. I tried it with both ImageMagick and GD configured, both was working. PHP is configured with 50mb.

It is strange that the error is not reproducable on your system... Please tell me if you experience it again.

**Comment by BastusIII** [comment]
@poeticpenguin 
I could reproduce the error now. It probably lies in not enough memory limit to process the image.
To increase that, you should change the value `memory_limit = 16M` in the php.ini. It is recommended to use 128M here.

This error does not always occur as it depends on the current server load when the memory is allocated.

Hope that helps for the future.

**Comment by poeticpenguin** [comment]
It seems like you are right. I've increased now the value in the PHP-ini file, so that it won't happen again. :)

Yes, i don't understand it either why i didn't get the error "_...it exceeds the file limit_", but it's ok.

I don't think that this problem is something that can be prevented within this module. Probably a F.A.Q would be nice.

> "If you plan to upload multiple  (and _huge_) pictures at once, please check if the memory_limit by PHP is set at about 128M"

, or something like that.

**Comment by BastusIII** [comment]
We plan to add that to the documentation :)

>If you plan to upload multiple (and huge) pictures at once, please check if the memory_limit by PHP is set at about 128M
