### ISSUE TITLE
Issue: Uploading multiple files sometimes causes the page not to reload

### ISSUE THREAD

**Issue by BastusIII** [humhub/humhub-modules-gallery#2]

**Comment by Felli** [comment]
To add onto this, it also affects posts on profiles/spaces, meaning it will show one image and just a link to the other image(s) that are uploaded.

**Comment by buddh4** [comment]
@Felli currently there is only one stream entry per image, the same as with cfiles, so there is no merged content stream entry yet. Perhaps we find a solution for this in the future. The actual problem of the uploading issue is already resolved.
